// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/board-usability/AcessibilidadeELeitura.tsx": () => import("../components/mockups/board-usability/AcessibilidadeELeitura.tsx"),
  "./components/mockups/board-usability/HierarquiaDeInformacao.tsx": () => import("../components/mockups/board-usability/HierarquiaDeInformacao.tsx"),
  "./components/mockups/board-usability/InteracaoEAffordances.tsx": () => import("../components/mockups/board-usability/InteracaoEAffordances.tsx")
};
